### ISSUE TITLE
You should be able to set the config in there with

### ISSUE THREAD

**Issue by kcdc80** [snowzach/hassio-addons#17]
You should be able to set the config in there with 
```
{
  "server": {
    "port": "8080"
  },
......
```
I don't use hassio a bunch but that should get it.

I tried to do this but the server does not start, I have no errors in the logs. But when I do a port scan nothing is running on the port I specified (e.g. 8081).

How can I go forward? Any suggestions?

_Originally posted by @snowzach in https://github.com/snowzach/hassio-addons/issues/6#issuecomment-766087325_

**Comment by snowzach** [comment]
I have updated to a new version (DOODS2) Update your repo and install DOODS2. It should fix this issue. Re-open if now.

**Comment by psadeazevedo** [comment]
> I have updated to a new version (DOODS2) Update your repo and install DOODS2. It should fix this issue. Re-open if now.

@snowzach I'm trying to run DOODS2 in a docker container on Synology by changing the docker port to 8181, but seems, I'm not able to mount the container:

 docker run --name image-processing --restart=always --net=host -it -p 8081:8081 -v /docker/doods snowzach/doods2:latest

Digest: sha256:799563e41d7e0f5e24632abdfa16a3b6843f3e058f5fa55e69c9cc2e9b5c9511
Status: Downloaded newer image for snowzach/doods2:latest
2023-07-21 16:48:11,416 - doods.doods - INFO - Registered detector type:tflite name:default
2023-07-21 16:48:17,023 - doods.doods - INFO - Registered detector type:tensorflow name:tensorflow
/usr/local/lib/python3.8/dist-packages/torch/hub.py:286: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
YOLOv5 🚀 2023-7-21 Python-3.8.10 torch-2.0.1+cpu CPU

Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt to yolov5s.pt...
100%|

Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape...
2023-07-21 16:48:42,745 - doods.doods - INFO - Registered detector type:pytorch name:pytorch
2023-07-21 16:48:42,905 - uvicorn.error - INFO - Started server process [1]
2023-07-21 16:48:42,907 - uvicorn.error - INFO - Waiting for application startup.
2023-07-21 16:48:42,909 - uvicorn.error - INFO - Application startup complete.
2023-07-21 16:48:42,937 - uvicorn.error - ERROR - [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
2023-07-21 16:48:42,938 - uvicorn.error - INFO - Waiting for application shutdown.
2023-07-21 16:48:42,939 - uvicorn.error - INFO - Application shutdown complete.

**Comment by snowzach** [comment]
Remove `--net=host` and it should work...

**Comment by psadeazevedo** [comment]
> Remove `--net=host` and it should work...

Thank you for your quick feedback. Removing it enables the container to start:

Adding AutoShape...
2023-07-21 17:16:57,098 - doods.doods - INFO - Registered detector type:pytorch name:pytorch
2023-07-21 17:16:57,384 - uvicorn.error - INFO - Started server process [1]
2023-07-21 17:16:57,384 - uvicorn.error - INFO - Waiting for application startup.
2023-07-21 17:16:57,386 - uvicorn.error - INFO - Application startup complete.
**2023-07-21 17:16:57,390 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)**
^C2023-07-21 17:17:07,230 - uvicorn.error - INFO - Shutting down
2023-07-21 17:17:07,332 - uvicorn.error - INFO - Waiting for application shutdown.
2023-07-21 17:17:07,333 - uvicorn.error - INFO - Application shutdown complete.
2023-07-21 17:17:07,333 - uvicorn.error - INFO - Finished server process [1]


But then at HA level, seems we get connections issues:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/doods/image_processing.py", line 96, in setup_platform
    doods = PyDOODS(url, auth_key, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydoods/__init__.py", line 13, in __init__
    self.get_detectors()
  File "/usr/local/lib/python3.11/site-packages/pydoods/__init__.py", line 20, in get_detectors
    response = requests.get(self.url + "/detectors", **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
**requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.xxx.xxx', port=8181): Max retries exceeded with url: /detectors (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f802c111050>: Failed to establish a new connection: [Errno 111] Connection refused'))**

I had doods working like a charme before, but had it on a different machine (pi), now I moved all into a single place (synology docker) and here I have other container already working on 8080 which I can't really change the port. I would love to keep using it.

**Comment by snowzach** [comment]
It looks like it's overloading the connections to doods maybe... Do you get any detections working and then this happens?

**Comment by psadeazevedo** [comment]
> It looks like it's overloading the connections to doods maybe... Do you get any detections working and then this happens? The DOODS2 log looks like it starts and shuts down.

The container seems to be OK, let me share with you a full cycle:

![image](https://github.com/snowzach/hassio-addons/assets/37579814/6a03d482-5012-4424-9c73-07609daff812)

After this, rebooted HA several times, with doods running for already a couple minutes and I always get the following error while setting up the image_processing:
![image](https://github.com/snowzach/hassio-addons/assets/37579814/42433315-516a-465d-9f2f-9dbbe41d2cfa)
Which then has the details I posted above.

**Comment by snowzach** [comment]
Oh... sorry... change it to `-p 8081:8080`

**Comment by snowzach** [comment]
DOODS is listening on port 8080 inside the container and 8081 outside the container... so you need to tell it to map port 8081 outside to 8080 inside.. `-p 8081:8080` Right now you're trying to connect to port 8081 inside the container and nothing is listening.

**Comment by psadeazevedo** [comment]
> DOODS is listening on port 8080 inside the container and 8081 outside the container... so you need to tell it to map port 8081 outside to 8080 inside.. `-p 8081:8080` Right now you're trying to connect to port 8081 inside the container and nothing is listening.

Thank you! This was the trick, changing the internal to the one I want mapping to 8080, I'm able to start the image_processing properly! Appreciate the support @snowzach
