### ISSUE TITLE
Exception: 'TensorflowLite' object has no attribute 'input_data'

### ISSUE THREAD

**Issue by boswelja** [snowzach/hassio-addons#23]
Hey there! I recently tried converting yolov5m to a tflite model and loading it in my RPi4, however I get the below exception when I try to run detection
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/doods/api.py", line 47, in detect
    detect_response = self.doods.detect(detect_request)
  File "/opt/doods/doods.py", line 137, in detect
    ret = detector.detect(image)
  File "/opt/doods/detectors/tflite.py", line 78, in detect
    input_data = (np.float32(self.input_data) - input_mean) / input_std
AttributeError: 'TensorflowLite' object has no attribute 'input_data'
```

The steps to convert the model are documented here: https://github.com/ultralytics/yolov5/issues/251

Any ideas are much appreciated :)

**Comment by snowzach** [comment]
Most tensorflow lite models have an input tensort called input_data. Because you converted it, it does not have that. We'd have to figure out what the input tensor name was for that model.

**Comment by boswelja** [comment]
Thanks for the insight! It sounds like an issue on my end rather than an issue with DOODS, so I'll close this 🙂
